[project]
channels = ["conda-forge"]
name = "vprsm"
platforms = ["linux-64"]

[system-requirements]
cuda="12.0"  # Matches cudatoolkit and faiss compatibility in micromamba

[tasks]

[dependencies]
python="==3.11.6"
pytorch="==2.1.0"
opencv="==4.8.1"
scikit-image="==0.24.0"
scikit-learn="==1.3.2"
seaborn="==0.13.0"
pandas="==2.1.4"
cuda-compiler="==12.0"
faiss="==1.7.4"
imbalanced-learn="==0.12.3"
ipykernel="==6.26.0"
natsort="==8.4.0"
tabulate="==0.9.0"

